---
- name: set properties
  script: set-properties.sh
  environment:
    HDFS_NAMENODE_HOST: "{{ hdfs_namenode_host }}"
    HDFS_BLOCK_SIZE: "{{ hdfs_block_size }}"
  tags:
    - master
    - worker

- name: create volume directories
  script: volume-directories.sh
  tags:
    - master
    - worker

- name: start namenode
  script: start-namenode.sh
  tags:
    - master

- name: start datanode
  script: start-datanode.sh
  tags:
    - worker

- name: create user directories
  script: user-directories.sh
  tags:
    - master
